### ISSUE TITLE
Chat GPT Feedback Kapitel 8

### ISSUE THREAD

**Issue by BorisJentsch** [ofilla/sohler-vl-info1-2023#1]
Insgesamt ist das Dokument gut geschrieben und enthält viele korrekte Informationen über die Landau-Notation. Allerdings gibt es einige Fehler und Unklarheiten, die korrigiert werden sollten:

1. Im Abschnitt "Annahmen" sollte es heißen "Die Funktionen \(f\) und \(g\) haben den Definitionsbereich \(\mathbb N_0\) und sollten für große \(n\) asymptotisch nicht-negativ sein". Der Ausdruck "asymptotisch nicht-negativ sein" ist etwas unklar. Es wäre besser zu sagen, dass die Funktionen für alle \(n\) größer als ein bestimmtes \(n_0\) nicht-negativ sein sollten.

2. Im Abschnitt "Beweise" ist die Aussage, dass man die Landau-Notationen nicht in Beweisen verwenden darf, etwas irreführend. Es ist wahr, dass man in Beweisen vorsichtig mit der Landau-Notation umgehen muss, aber es ist nicht generell verboten, sie zu verwenden.

3. Im Abschnitt "Hierarchien" ist die Formulierung "\(\forall 2 \le b \in\mathbb R:\mathcal O(\log n) \subseteq\mathcal O(\log^2 n) \subseteq\mathcal O(\log^b n)\)" nicht korrekt. Es sollte heißen "\(\forall b \ge 2 :\mathcal O(\log n) \subseteq\mathcal O(\log^2 n) \subseteq\mathcal O(\log^b n)\)".

4. Im Abschnitt "Erweiterte \(\mathcal O\)-Notation" ist die Definition unklar. Es sollte besser erklärt werden, was \(n\) und \(m\) in diesem Kontext bedeuten.

5. Im Abschnitt "\(\omega\)-Notation" ist die Formel falsch. Es sollte heißen:
    $$
    \omega (g(n)) = \{
        \text{Funktion} f(n) |
        \forall c\in\mathbb R_+:\exists n_0\in\mathbb N:
        \forall n\ge n_0: 0 \le c\cdot g(n) < f(n)
    \}
    $$

6. Die letzte Formel ist auch falsch. Es sollte heißen:
    $$
    f(n) \in \omega(g(n)) \Leftrightarrow g(n) \in o(f(n))
    $$

Bitte beachten Sie, dass diese Korrekturen auf meinem Wissen bis September 2021 basieren. Es ist möglich, dass es seitdem neue Erkenntnisse oder Änderungen in der Notation gegeben hat.

**Comment by ofilla** [comment]
Danke für das Feedback, es war auf jeden Fall ein Fehler drin. Solved in 144792ebe4453c6e0a48c68080df6119232dd882.
