### ISSUE TITLE
Chat GPT Feedback Kapitel 3: wichtige Algorithmen 

### ISSUE THREAD

**Issue by BorisJentsch** [ofilla/sohler-vl-info1-2023#3]
1. In the section "Insertion Sort", you stated that "Die Worst-Case-Laufzeit von InsertionSort ist in \(\Omega(n^2)\)." and then "Korollar: Die Worst-Case-Laufzeit von InsertionSort ist \(\Theta(n^2)\)." This might be a bit confusing because \(\Omega\) notation is used for lower bounds and \(\Theta\) notation is used when we have tight bounds. If you're sure that the worst-case time complexity of Insertion Sort is \(\Theta(n^2)\), you might not need to mention the \(\Omega(n^2)\) part.

2. In the section "$n$-Ziffer-Integer Multiplikation", you mentioned that "Effizienter wird es, wenn wir die Identität \((A+B)(C+D)=AC+BC+AD+BD\) verwenden." However, the correct identity is \((A+B)(C+D)=AC+BD+AD+BC\).

3. In the section "Algorithmus von Strassen (Matrixmultiplikation)", you mentioned that "Die Laufzeit ist dann \(T(n)\in \mathcal \subseteq\mathcal O(n^3)\)". However, \(n^{\log_2 8}\) simplifies to \(n^3\), so you might want to just say that the runtime is \(\mathcal O(n^3)\).

4. In the section "Fibbonacci-Zahlen", you mentioned that "\(\mathrm{FibRecursive}\) hat eine Laufzeit von \(T(n)\in\Omega(1.6^n)\)". However, the time complexity of the recursive Fibonacci algorithm is usually given as \(O(2^n)\), not \(\Omega(1.6^n)\).

5. In the section "Partition", you mentioned that "Partition ist $NP$-vollständig." However, it's more common to say that the Partition problem is NP-complete.

6. In the section "SubsetSum", you mentioned that "\(\mathrm{SubsetSum}(A, U, n)\) hat eine Laufzeit von \(T(n)=\mathcal O(nU)\)." However, the time complexity of the Subset Sum problem is usually given as \(O(nU)\), not \(T(n)=\mathcal O(nU)\).

Please note that these are potential issues and might not be actual errors depending on the context. I recommend checking these sections and making sure that they accurately represent the information you want to convey.

**Comment by ofilla** [comment]
Thanks for the feedback. Solved in commit 3d193300463ad3704387c717410d7844afd58009.
